apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bd47hkx2b-python 
  janus-idp.io/tekton: bd47hkx2b-python
  backstage.io/kubernetes-id: bd47hkx2b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bd47hkx2b-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml